services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elrincon-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      # Pasamos las variables del .env al contenedor
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGSCHEMA=${PGSCHEMA}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    networks:
      - harco_network

networks:
  harco_network:
    name: harco_network
    external: true