"""add cv_url column

Revision ID: 7969bead0e27
Revises: 
Create Date: 2026-03-20 14:52:39.958815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7969bead0e27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_settings_id'), table_name='site_settings')
    op.drop_table('site_settings')
    op.add_column('heroes', sa.Column('cv_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'cv_url')
    op.create_table('site_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('site_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('legal_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slogan', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('copyright_notice', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('social_networks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('site_settings_pkey'))
    )
    op.create_index(op.f('ix_site_settings_id'), 'site_settings', ['id'], unique=False)
    # ### end Alembic commands ###
